language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - pytest tests/ --cov=sort
  - python sort.py
  - cp README.md docs/index.md
  - mkdocs build

deploy:
  provider: pages
  local-dir: site
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
